TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 0.1
  acc_lim_x: 0.10
  acc_lim_y: 0.10

  holonomic_robot: false
  meter_scoring: true
 
