local_costmap:
  global_frame: map
  robot_base_frame: np
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.1
inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     5.9
